#!/bin/bash


############################
### INSTALL DEPENDENCIES ###
############################

DEPS=(wget make opensc openssl-devel lzo-devel pkcs11-helper-devel pam-devel)

echo "Checking dependencies:"
for PKG in ${DEPS[*]}
do
	if rpm -q $PKG > /dev/null 2>&1; then
		echo -e "\xE2\x9C\x94 $PKG is already installed."
	else
		echo -en "? Installing $PKG ..."\\r
		dnf install $PKG -y >/dev/null 2>&1
		echo -e "\xE2\x9C\x94 $PKG has been installed."
	fi
done
echo ""
#######################
### INSTALL OPENVPN ###
#######################

VERSION="2.4.6"
TAR="openvpn-${VERSION}.tar.gz"
LINK="https://swupdate.openvpn.org/community/releases/${TAR}"

echo "Checking OpenVPN:"

if rpm -q openvpn > /dev/null; then
	echo "removing old rpm based openvpn installation."
	dnf remove openvpn -y > /dev/null
fi

if which openvpn > /dev/null 2>&1 && openvpn --version | grep "enable_systemd=no" > /dev/null && openvpn --version | grep "enable_pkcs11=yes" > /dev/null; then
	echo -e "\xE2\x9C\x94 openvpn is already installed correctly."
else
	echo -en "? Installing openvpn from source ..."\\r
	wget $LINK > /dev/null 2>&1 && tar zxvf $TAR > /dev/null && \
		(cd openvpn-${VERSION} && ./configure --enable-systemd=no --enable-pkcs11=yes \
		&& make && make install) && \
		rm -rf openvpn-${VERSION} ${TAR}*
	echo -e "\xE2\x9C\x94 openvpn has been installed from source."
fi
echo ""

if [ -f /usr/local/sbin/openvpn ]; then
	mv /usr/local/sbin/openvpn /usr/sbin/
fi

#################################
### GET YUBIKEY SERIALIZED ID ###
#################################

PKCS11_PATH="/usr/lib64/pkcs11/opensc-pkcs11.so"

if [ ! -f $PKCS11_PATH ]; then
	echo "Please enter correct opensc-pkcs11.so path"
	exit 1
fi

while true
do
	if openvpn --show-pkcs11-ids /usr/lib64/pkcs11/opensc-pkcs11.so | grep -i "serialized id" > /dev/null; then
		SERIAL=$(openvpn --show-pkcs11-ids /usr/lib64/pkcs11/opensc-pkcs11.so | grep -i "serialized id" | tr -s ' ' | cut -d ' ' -f 4)
		break
	else
		echo "Please insert your yubikey device and press [ENTER]"
		read
	fi
done


#######################
### GENERATE CONFIG ###
#######################

CLIENT=test

echo "Generating OpenVPN client configuration file:"
cat <<EOF > ${CLIENT}.conf
# This files is generated by script

client
pull
dev tun
proto udp
remote 35.185.63.141 1194
resolv-retry infinite
nobind
user nobody
group nobody
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
auth-nocache
verb 4
pkcs11-providers ${PKCS11_PATH}
pkcs11-id '${SERIAL}'
<ca>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</ca>
<tls-crypt>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
-----END OpenVPN Static key V1-----
</tls-crypt>
EOF

echo -e "\xE2\x9C\x94 ${CLIENT}.conf has been generated."
echo ""
echo ""
echo "OpenVPN client has been successfully installed."
echo "You can now use 'sudo openvpn ${CLIENT}.conf' to connect to VPN server."
echo "You will need to additionally enter PIN code of your Yubikey device."
exit 0
